# Generated by Django 3.1 on 2020-08-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='the_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='the_level',
            new_name='level',
        ),
    ]
