# Generated by Django 3.1 on 2020-08-25 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='the_level',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='the_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lvl', to='slides.level'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slides.level'),
        ),
        migrations.AlterField(
            model_name='level',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro', to='slides.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sch', to='slides.school'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to=models.CharField(max_length=255))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.school')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
