# Generated by Django 3.0.8 on 2020-08-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='program',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
    ]
