# Generated by Django 3.1 on 2020-08-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_auto_20200823_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
