# Generated by Django 3.1 on 2020-08-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_auto_20200825_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='location',
            new_name='locatio',
        ),
    ]
