# Generated by Django 3.0.8 on 2020-08-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_auto_20200819_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.School'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.University'),
        ),
    ]
