# Generated by Django 3.0.8 on 2020-08-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0004_auto_20200819_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
