# Generated by Django 3.1 on 2020-08-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_auto_20200823_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
    ]
