# Generated by Django 3.1 on 2020-08-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_document_location_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='location_value',
        ),
    ]
