# Generated by Django 3.1 on 2020-08-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0006_remove_document_location_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=None),
        ),
    ]
