# Generated by Django 3.1 on 2020-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0009_auto_20200825_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
