# Generated by Django 3.1 on 2020-08-25 19:16

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0011_auto_20200825_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=django.db.models.fields.CharField),
        ),
    ]
