# Generated by Django 3.1 on 2020-08-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0012_auto_20200825_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=models.CharField(max_length=255)),
        ),
    ]
