# Generated by Django 3.1 on 2020-08-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0014_auto_20200825_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='locale',
            field=models.CharField(default='abednego', max_length=256),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=models.CharField(default='abednego', max_length=256)),
        ),
    ]
