# Generated by Django 3.1 on 2020-08-25 22:08

from django.db import migrations, models
import slides.models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0019_auto_20200825_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=slides.models.add_path),
        ),
    ]
