# Generated by Django 3.1 on 2020-08-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0021_document_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='location',
            new_name='slug',
        ),
    ]
