# Generated by Django 3.1 on 2020-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0024_auto_20201201_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='document',
            name='topic',
            field=models.CharField(max_length=10000),
        ),
    ]
