# Generated by Django 3.1 on 2020-12-01 12:17

from django.db import migrations, models
import slides.models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0025_auto_20201201_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(max_length=1000, upload_to=slides.models.add_path),
        ),
    ]
